Python_Web_Basic_Exam_prep/common/urls.py
from django.urls import path

from Python_Web_Basic_Exam_prep import common
from Python_Web_Basic_Exam_prep.common.views import home, create, edit, delete, details

urlpatterns = [
     path('', home, name='home'),
     path('create/', create, name='crete'),
     path('edit/<int:id>' , edit, name='edit'),
     path('delete/<int:id>', delete, name='delete'),
     path('details/<int:id>', details, name='details'),
]

Python_Web_Basic_Exam_prep/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Python_Web_Basic_Exam_prep.common.urls')),
]

Python_Web_Basic_Exam_prep/common/models.py
from django.db import models

# Create your models here.
class Recipe(models.Model):
    title = models.CharField(
        max_length=30
    )
    image_url = models.URLField()
    description = models.TextField()
    ingredients = models.CharField(
        max_length=250
    )
    time = models.IntegerField()

Python_Web_Basic_Exam_prep/common/forms.py
from django import forms

from Python_Web_Basic_Exam_prep.common.models import Recipe


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields ='__all__'

class CreateRecipeForm(RecipeForm):
    pass

class EditRecipeForm(RecipeForm):
    pass

class DeleteRecipeForm(RecipeForm):
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        for ( _, field) in self.fields.items():
            field.widget.attrs['disabled'] = 'disabled'

Python_Web_Basic_Exam_prep/common/views.py
from django.shortcuts import render, redirect


# Create your views here.

from Python_Web_Basic_Exam_prep.common.core.create_recipe import get_recipe
from Python_Web_Basic_Exam_prep.common.forms import EditRecipeForm, CreateRecipeForm, DeleteRecipeForm
from Python_Web_Basic_Exam_prep.common.models import Recipe


def home(request):
    recipe = get_recipe()
    if not recipe:
        return redirect('create recipe')
    recipe = Recipe.objects.all

    context = {
          'recipe': recipe
    }
    return render(request, 'index.html', context)


def create(request):
    if request.method == 'POST':
        form = CreateRecipeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = CreateRecipeForm()

    context = {
        'form': form,
    }
    return render(request, 'create.html', context)


def edit(request, pk):
    recipe = Recipe.objects.get(pk=pk)
    if request.method == 'POST':
        form = EditRecipeForm(request.POST, instance=recipe)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = EditRecipeForm(instance=recipe)

    context = {
        'form': form
    }
    return render(request, 'edit.html', context)



def delete(request, pk):
    recipe = Recipe.objects.get(pk=pk)
    if request.method == 'POST':
        recipe.delete()
        form = DeleteRecipeForm(request.POST, instance=recipe)

    else:
        form = DeleteRecipeForm(instance=recipe)

    context = {
        'form': form
    }
    return render(request, 'delete.html', context)


def details(request, pk):
    recipe = Recipe.objects.get(pk=pk)
    if not recipe:
        return redirect('home')
    recipe = Recipe.objects.get(pk=pk)
    context = {
        'recipe': recipe,
    }
    return render(request, 'details.html', context)

templates/create.html
{% load static %}
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%  static 'css/style.css'%}">
    <title>Recipes</title>
</head>

<body>
     
 <nav>
    <ul>
        <img src="./static/images/chef.png" alt="chef">
        <li class="title"><a href="/">Recipes</a></li>
        <li><a href="/create">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">
        
<h1>Create Recipe</h1>
<div class="items-container">
    <div class="item">
        <form method="POST" action={% url "create.html" %}>
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
</div>

    </div>


</body></html>

templates/delete.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./static/css/style.css">
    <title>Recipes</title>
</head>

<body>
     
 <nav>
    <ul>
        <img src="./static/images/chef.png" alt="chef">
        <li class="title"><a href="/">Recipes</a></li>
        <li><a href="./create">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">
        
<h1>Delete Recipe</h1>
<div class="items-container">
    <div class="item">
        <form method="POST">
            <label for="title">Title</label>
            <input type="text" name="title" value="Homemade Chicken Soup" maxlength="30" disabled="" required="" id="id_title">
            <label for="imageURL">Image URL</label>
            <input type="url" name="image_url" value="https://i.ytimg.com/vi/o91gT73mQhg/maxresdefault.jpg" maxlength="200" disabled="" required="" id="id_image_url">
            <label for="description">Description</label>
            <textarea name="description" cols="40" rows="10" disabled="" required="" id="id_description">Put the chicken, carrots, celery and onion in a large soup pot and cover with cold water. Heat and simmer, uncovered, until the chicken meat falls off of the bones (skim off foam every so often).
Take everything out of the pot. Strain the broth. Pick the meat off of the bones and chop the carrots, celery and onion. Season the broth with salt, pepper and chicken bouillon to taste, if desired. Return the chicken, carrots, celery and onion to the pot, stir together, and serve.</textarea>
            <label for="ingredients">Ingredients</label>
            <input type="text" name="ingredients" value="1 (3 pound) whole chicken, 4 medium (blank)s carrots halved, 4 stalks celery halved, 1 large onion halved, water to cover, salt and pepper to taste, 1 teaspoon chicken bouillon granules" maxlength="250" disabled="" required="" id="id_ingredients">
            <label for="time">Time (Minutes)</label>
            <input type="number" name="time" value="30" disabled="" required="" id="id_time">
            <input type="submit" class="button delete" value="Delete">
        </form>
    </div>
</div>

    </div>


</body></html>

templates/details.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./static/css/style.css">
    <title>Recipes</title>
</head>

<body>
     
 <nav>
    <ul>
        <img src="./static/images/chef.png" alt="chef">
        <li class="title"><a href="/">Recipes</a></li>
        <li><a href="./create">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">
        
<h1>Recipe Details</h1>
        <div class="items-container">
            <div class="item">
                <h2>Homemade Chicken Soup</h2>
                <img class="detail-img" src="https://i.ytimg.com/vi/o91gT73mQhg/maxresdefault.jpg" alt="recipe-image">
                <div class="time">
                    <img src="./static/images/clock.png">
                    <p>30min</p>
                </div>
                <h3>Ingredients</h3>
                <ul>
                    
                        <li>1 (3 pound) whole chicken</li>
                    
                        <li>4 medium (blank)s carrots halved</li>
                    
                        <li>4 stalks celery halved</li>
                    
                        <li>1 large onion halved</li>
                    
                        <li>water to cover</li>
                    
                        <li>salt and pepper to taste</li>
                    
                        <li>1 teaspoon chicken bouillon granules</li>
                    
                </ul>
                <h3>How to prepare?</h3>
                <div class="recipe-info-full">
                    Put the chicken, carrots, celery and onion in a large soup pot and cover with cold water. Heat and simmer, uncovered, until the chicken meat falls off of the bones (skim off foam every so often).
Take everything out of the pot. Strain the broth. Pick the meat off of the bones and chop the carrots, celery and onion. Season the broth with salt, pepper and chicken bouillon to taste, if desired. Return the chicken, carrots, celery and onion to the pot, stir together, and serve.
                </div>
                <div class="buttons-container">
                    <a class="button edit" href="./edit.html">Edit</a>
                    <a class="button delete" href="./delete.html">Delete</a>
                </div>
            </div>
        </div>

    </div>


</body></html>

templates/edit.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./static/css/style.css">
    <title>Recipes</title>
</head>

<body>
     
 <nav>
    <ul>
        <img src="./static/images/chef.png" alt="chef">
        <li class="title"><a href="/">Recipes</a></li>
        <li><a href="./create">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">
        
<h1>Edit Recipe</h1>
<div class="items-container">
    <div class="item">
        <form method="POST">
            <label for="title">Title</label>
            <input type="text" name="title" value="Homemade Chicken Soup" maxlength="30" required="" id="id_title">
            <label for="imageURL">Image URL</label>
            <input type="url" name="image_url" value="https://i.ytimg.com/vi/o91gT73mQhg/maxresdefault.jpg" maxlength="200"  required="" id="id_image_url">
            <label for="description">Description</label>
            <textarea name="description" cols="40" rows="10"  required="" id="id_description">Put the chicken, carrots, celery and onion in a large soup pot and cover with cold water. Heat and simmer, uncovered, until the chicken meat falls off of the bones (skim off foam every so often).
Take everything out of the pot. Strain the broth. Pick the meat off of the bones and chop the carrots, celery and onion. Season the broth with salt, pepper and chicken bouillon to taste, if desired. Return the chicken, carrots, celery and onion to the pot, stir together, and serve.</textarea>
            <label for="ingredients">Ingredients</label>
            <input type="text" name="ingredients" value="1 (3 pound) whole chicken, 4 medium (blank)s carrots halved, 4 stalks celery halved, 1 large onion halved, water to cover, salt and pepper to taste, 1 teaspoon chicken bouillon granules" maxlength="250"  required="" id="id_ingredients">
            <label for="time">Time (Minutes)</label>
            <input type="number" name="time" value="30" required="" id="id_time">
            <input type="submit" class="button edit" value="Edit">
        </form>
    </div>
</div>

    </div>


</body></html>

templates/index.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Recipes</title>
</head>

<body>

    <nav>
        <ul>
            <img src="./static/images/chef.png" alt="chef">
            <li class="title"><a href="/">Recipes</a></li>
            <li><a href="./create.html">Add Recipe</a></li>
        </ul>
    </nav>
    <div class="container">

        <h1>My Recipes</h1>
        <h2>There are no recipes.</h2>
        <div class="items-container">
            <div class="item">
                <h2>Homemade Chicken Soup</h2>
                <img class="detail-img" src="https://i.ytimg.com/vi/o91gT73mQhg/maxresdefault.jpg" alt="recipe-image">
                <div class="recipe-info">
                    Put the chicken, carrots, celery and onion in a large soup pot and cover with cold water. Heat and simmer, uncovered, until the chicken meat falls off of the bones (skim off foam every so often). Take everything out of the pot. Strain the broth. Pick
                    the meat off of the bones and chop the carrots, celery and onion. Season the broth with salt, pepper and chicken bouillon to taste, if desired. Return the chicken, carrots, celery and onion to the pot, stir together, and serve.
                </div>
                <div class="buttons-container">
                    <a class="button detail" href="./details.html">Details</a>
                    <a class="button edit" href="./edit.html">Edit</a>
                    <a class="button delete" href="./delete.html">Delete</a>
                </div>
            </div>

            <div class="item">
                <h2>Cardamom Maple Salmon (Edit)</h2>
                <img class="detail-img" src="https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F1122494.jpg&amp;w=596&amp;h=596&amp;c=sc&amp;poi=face&amp;q=85" alt="recipe-image">
                <div class="recipe-info">
                    Stir salt, paprika, cardamom, coriander, and black pepper together in a bowl. Add oil and maple syrup and stir until evenly combined. Preheat a non-stick frying pan over medium-high heat, about 350 degrees F (175 degrees C). Dredge salmon pieces through
                    the maple syrup mixture until evenly coated on all sides. Cook salmon in the preheated pan until fish flakes easily with a fork, 5 to 7 minutes per side.
                </div>
                <div class="buttons-container">
                    <a class="button detail" href="./details.html">Details</a>
                    <a class="button edit" href="./edit.html">Edit</a>
                    <a class="button delete" href="./delete.html">Delete</a>
                </div>
            </div>

        </div>

    </div>


</body>

</html>